### ISSUE TITLE
MRTK Speech Input stops responding after exiting application or putting headset to sleep

### ISSUE THREAD

**Issue by ARGs-code** [microsoft/MixedRealityToolkit-Unity#10527]
## Describe the bug

When my application runs I have speech commands and hand interactions. User can execute all actions via voice commands or hand interactions via 3D buttons. If a user puts the headset to sleep, or does not completely close the application, the next time they open the app voice commands will no longer function.

## To reproduce

I am in the process of trying to reproduce this with a stripped down project. My current project doesn't throw any errors in the UnityPlayerLog or while compiling and deploying. I am also using Spatial Awareness, Hand Tracking and Eye Tracking. The application works entirely as expected, except for this issue with 0 response from the Speech Input System. System level speech commands still function.

## Expected behavior

Speech commands work in the application even after re-entering the application after Headset being put to sleep or leaving application for shell environment.

## Screenshots

N/A

## Your setup (please complete the following information)

- Unity Version 2020.3.30f1
- MRTK Version v2.7

## Target platform (please complete the following information)
- HoloLens 2

## Additional context

I can provide a player logfile if it would be helpful.

**Comment by MaxWang-MS** [comment]
It seems like this is a duplicate of #10249, please find a workaround in that issue.

**Comment by ARGs-code** [comment]
> It seems like this is a duplicate of #10249, please find a workaround in that issue.

I have tried that solution. It does not resolve my issue.

**Comment by ARGs-code** [comment]
I have also tried Stopping and Restarting the Phrase recognizer. That also does not resolve this issue.

**Comment by ARGs-code** [comment]
@MaxWang-MS  I am likely going to repost this ticket tomorrow as my issue has not been resolved by your work around or any other work around I have found so far.

**Comment by MaxWang-MS** [comment]
Please post under the existing issue given this is a duplicate. This bug is external to MRTK and [according to Unity](https://fogbugz.unity3d.com/default.asp?1276443_feij5mjans4g1jds) they have intentionally decided to not fix it. Please consider open another ticket with Unity and/or file an OS bug ticket in the HoloLens 2 feedback hub app.

**Comment by ARGs-code** [comment]
@MaxWang-MS 

The link you provided states at the end that this is a Windows API or OS Bug apparently- 

"This issue appears to be Windows API or OS bug as we're able to reproduce the problem using the Microsoft Speech Recognition samples:
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SpeechRecognitionAndSynthesis.

To work around the problem, the Speech Recognition objects (KeywordRecognizer, DictationRecognizer, etc.) should be re-initialized and restarted after the app is restored.

We appreciate your contribution to the Unity product."

Reinitializing the Speech Recognition objects does not work.

**Comment by ARGs-code** [comment]
I will post under the "existing" issue. Which is also closed. Thank you for your help.

**Comment by davidkline-ms** [comment]
@ARGs-code, thanks for the report! 

To clarify what @MaxWang-MS said regarding this being an external issue means MRTK cannot directly fix it. It must be addressed at the operating system level. I highly recommend filing a Feedback Hub issue from your device. That will give the OS team the information they need to start investigating. 

Thank you for your understanding.

**Comment by ARGs-code** [comment]
Thanks for the clarification David, I did misunderstand the external designation. Sorry about that.

I'll file another feedback hub issue to the OS Team.

**Comment by davidkline-ms** [comment]
No stress at all. :smile:

**Comment by ARGs-code** [comment]
I filed Feedback Hub Issues a while back and we are still encountering this issue. Is there any other venue available for me to try and push this along? Or is the feedback hub the only option?
