### ISSUE TITLE
[Bug] Cannot show Oculus controllers with hand meshes

### ISSUE THREAD

**Issue by pokemon9757** [microsoft/MixedRealityToolkit-Unity#10562]
## Bug description: 

Cannot show Oculus controllers with hand meshes no matter which settings I change to. The controllers are only being shown as: 
- Oculus Controller by default
- Arrows: 
![image](https://user-images.githubusercontent.com/59111886/165510055-a490a0c6-a52c-4eb2-b002-35a48e1cb670.png)
- Or empty with just pointers 

## To reproduce:

- Have attempted with Oculus's hand tracking enabled and disabled.
- Connected Oculus Quest to my laptop via USB-C port. 
- I followed the steps in [this video](https://www.youtube.com/watch?v=rb5GZVDREdk) to set up MRTK for my Oculus Quest. 
- Have done a build of the project.

## Expected behaviour:

From the video, I expect the controllers to be shown with hand meshes similar to the end of the attached video.
![image](https://user-images.githubusercontent.com/59111886/165510447-2782b7f3-4277-446c-98ce-ae4f4c3d7bf5.png)

## My setup:

- Unity Version 2020.3.26f1
- MRTK Version v2.7.3.0

## Target platform 

- Oculus Quest / Oculus Quest 2

**Comment by RogPodge** [comment]
Hey there, sorry for the late response.

On the Quest itself, you have to make sure that your quest is set to use the hand-tracking mode. If you use the controllers at all, you have to re-set the quest to use hands via set of quest menu options.

Any other issues you see should be fixed in our next release:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10568
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10574

**Comment by pokemon9757** [comment]
Hi @RogPodge,

Thank you for your response! I assume you are referring to the hand-tracking mode in Settings/Hands and Controllers/Hands? I have already enabled that before I did the above steps. It still doesn't show my hands.
