### ISSUE TITLE
Keyboard Input in MRTK3

### ISSUE THREAD

**Issue by HaiKonofanDesu** [microsoft/MixedRealityToolkit-Unity#11196]
## Overview
I want to implement a small settings menue where you can edit the IP Adress of the server. Sadly no matter what I do with the TMP Input Field I can't open a Keyboard. So far I saw 0 tutorials/ explnations on how to do it in MRTK3 and all MRTK2 sources I found did not work. Can someone explain to me how it works with MRTK3?
## Expected behavior
I have a Script I can attach to the Input field and it works/ I can use a given Prefab to open up the Keyboard ad type
## Actual behavior
No matter what Script I attach no keyboard opens.

## Unity editor version
2020.3.41f1

## Mixed Reality Toolkit release version
0.9 (on newer Versions my Near Menue Prefab I used is gone)

**Comment by MaxWang-MS** [comment]
Could you let us know what device are you targeting? There are docs and samples for MRTK2 and samples for MRTK3.
MRTK2 docs: https://learn.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk2/features/experimental/mixed-reality-keyboard
MRTK2 samples: MixedRealityKeyboardExample.unity in the [samples we ship](https://learn.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk2/running-example-scenes)
MRTK3 samples: UnityProjects/MRTKDevTemplate/Assets/Scenes/InputFieldExamples.unity

**Comment by MaxWang-MS** [comment]
Tagging @Zee2 for the disappeared near menu prefab.

**Comment by Zee2** [comment]
Near menu prefab issue is addressed in the most recent release notes.

**Comment by HaiKonofanDesu** [comment]
@Zee2 thanks for the Info! Will try this out later

@MaxWang-MS My current Target is the HoloLens 2.
I currently use MRTK3 so the MRTK2 links sadly don't help.
Could you please explain a bit more where I can find the MRTK3 samples? I can't seem to find the MRTKDevTemplate Repo

**Comment by HaiKonofanDesu** [comment]
Short Update:
I tried to update my Project to MRTK pre 12 and now have the desired Input Field prefabs I wanted. Sadly the update means I need to completely redo my NearMenue as even with the Fix a lot of stuff changed (where the Text is in the prefab for example. My apps wants to change the Text and Color in real time) so I need to rewrite my code for this. 
Also the button prefab seems to have changed as well? At least I have missing prefabs here as well and the "new" prefabs I can find in my folder don't seem to work or look weird.
This is the "Action Button prefab" dragged into my scene looking waaay bigger than anything else
![image](https://user-images.githubusercontent.com/101000327/201628226-021a37e7-714e-4421-972b-1ac9768217de.png)

But when I deselect it there is.. nothing? Am I using the wrong prefab?
![image](https://user-images.githubusercontent.com/101000327/201628106-eb67f93a-95ee-4d09-8602-d03661e4fc1c.png)

**Comment by HaiKonofanDesu** [comment]
![image](https://user-images.githubusercontent.com/101000327/201664720-2949444c-7d17-4015-a8c6-b31e2a86ca4a.png)
Seems like in the new NearMenue Prefab the text is not properly placed? Or do I use the wrong text?

**Comment by HaiKonofanDesu** [comment]
Just set up a new Project with only the MRTK3 pre 12 loaded it. Still can't see any prefabs. TextInput, Buttons and Dialogues are all transparent. If I click on the Prefab in the prefab viewer everything looks good tho.. Not sure if it's a problem with Unity 2020

**Comment by HaiKonofanDesu** [comment]
Preview (double click on Prefab) shows everything fine
![image](https://user-images.githubusercontent.com/101000327/201954968-3915652a-17d7-4071-be91-5f2412cb4209.png)

Dragging it into the scene makes it look like this:
![image](https://user-images.githubusercontent.com/101000327/201955156-7d6b7694-e38f-4253-a8c1-df08612fe064.png)

Tried it on a second PC as well. Still same problem.

Would really appreciate some help.

**Comment by MaxWang-MS** [comment]
Hi @HaiKonofanDesu, looking at your screenshots it seems that you were using our canvas-based components without a canvas. You need to parent our canvas-based components (e.g. action button, canvas dialog) under a canvas. In the prefab view Unity automatically creates a `Canvas (Environment)` GameObject at the root level so that's why you are able to "see" the prefab in prefab viewing mode.

**Comment by MaxWang-MS** [comment]
For more information, please refer to [our docs](https://learn.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/overview) and [a talk by our team member @Zee2 (linked to the part covering our canvas-based UI)](https://youtu.be/9GmyInQ1yjw?t=1912).

**Comment by MaxWang-MS** [comment]
The docs for some individual components are a bit outdated but we will be updating them soon.

**Comment by MaxWang-MS** [comment]
Given the original question regarding text field prefab has been answered, I am closing this issue. If you have any follow-up questions on our UI components, please open a new issue for better visibility for the community.

**Comment by HaiKonofanDesu** [comment]
@MaxWang-MS Just tried it and it works. I thought I have tried it before but maybe something was odd there. Thanks for the detailed answer! Ye I really have problems with the docs so any links like that are really helpful! I'm exited for the new doc as with each new update a lot of stuff changes so have a somewhat up to date doc would be really nice.

If I have any other questions I make a new post. So again thanks for the help!
