### ISSUE TITLE
Unable to Deploy from Build Window

### ISSUE THREAD

**Issue by mavasher** [Microsoft/MixedRealityToolkit-Unity#1834]
## Overview
Unable to deploy to Hololens. 

## Expected Behavior
After successfully building a barebones project and building the Appx, the program deploys correctly to the Hololens

## Actual Behavior.
Builds project correctly. Appears to connect to Hololens.
Does not deploy to the Hololens when pressing "Install"

## Steps to reproduce
The correct WiFi IP address is provided and when I press "Connect" under deploy options, I get the correct Hololens device name. When I press "Open Device Portal" - IE opens the Hololens Device Portal correctly without issue. 

When I press "Install" - I get a Network Error: Request timeout. 
Then "Failed to install [APP].appx on [DEVICE].

See screenshot. 
![image](https://user-images.githubusercontent.com/13334553/37381755-2571fbba-26fc-11e8-9dde-a8afd6516688.png)

## Unity Editor Version
2017.3.1f1

## Mixed Reality Toolkit Release Version
2017.2.1.2

## Hololens OS Version
10.0.14393.2068

## Windows OS Version (Development PC)
10.0.16299 Build 16299

**Comment by jerrygg** [comment]
Me too .

**Comment by StephenHodgson** [comment]
You can reach the device via device portal?

**Comment by StephenHodgson** [comment]
Try changing the timeout for the webrequest to be longer in the BuildAndDeployPortal.

**Comment by mavasher** [comment]
@StephenHodgson : This fixed it!

in **BuildDeployPortal.cs** I changed line 30 and line 31 to the following:
`private const float TimeOut = 20.0f;`
`private const float MaxWaitTime = 40.0f;`

**Comment by XPav** [comment]
The same increase to the timeout allowed for deploying for me also.

**Comment by StephenHodgson** [comment]
Fixed in #1904

**Comment by davidkline-ms** [comment]
@StephenHodgson is this change also part of #2127?

**Comment by StephenHodgson** [comment]
No, but I could still add it. Not sure if I ported the rest time outs that I have in my private branch.

**Comment by LaylaGor** [comment]
I got the latest release but this issue still exists. @StephenHodgson  do I need to manually fix it?

**Comment by LaylaGor** [comment]
> I think it depends on the size of your build. I'd increase the timeout and wait time described above.

I doubled it and its working now

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
