### ISSUE TITLE
[May18] Tooltip example scene's labels position

### ISSUE THREAD

**Issue by cre8ivepark** [Microsoft/MixedRealityToolkit-Unity#2157]
## Overview
In the Tootip example scene, labels are in weird location.
![2018-05-23 16_17_52-unity 2017 4 3f1 64bit - tooltipexamples unity - mrtk-rc - universal windows p](https://user-images.githubusercontent.com/13754172/40456245-1d269ef8-5ea5-11e8-8835-f3fe9367ae3f.png)

## Expected Behavior
It should be close to the object

## Unity Editor Version
2017.2.1p2 and 2017.4.3f1

## Mixed Reality Toolkit Release Version
2017.4.0.0 Release Candidate

**Comment by cre8ivepark** [comment]
Fixed in #2158

**Comment by GodfreyD7** [comment]
I have a slight problem with the the tooltip. It won't attach to my 3dobj. If you could please let me know where I'm going wrong that would be great! Thanks!
Attached is a picture of the problem. In the tooltip connector I've linked it to the combustor but it places the anchor all the way at the bottom. I've followed everything from the tooltip example but still no luck. Thanks in advance for the help!

Respectfully,
Godfrey D'souza


![2019-02-22](https://user-images.githubusercontent.com/47899856/53263376-39e10f80-36a7-11e9-81e5-62edfaa284dc.png)
