### ISSUE TITLE
MRTK does not build for iOS configured build target

### ISSUE THREAD

**Issue by FejZa** [Microsoft/MixedRealityToolkit-Unity#2336]
## Overview
When building an application that targets WMR and iOS, the project cannot build for iOS, because scripts in the MRTK do not compile.

## Expected Behavior
I can build for iOS even when I have MRTK in my project.

## Actual Behavior
I cannot build for iOS

## Steps to reproduce
- Create new Unity project (2014.4+)
- Import MRTK package
- Set iOS as target platform
- Try building

## Unity Editor Version
2018.1

## Mixed Reality Toolkit Release Version
2017.4

## Example build errors
[Unity] Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/GLTFUnityHelpers.cs(59,23): error CS0246: The type or namespace name `GLTF' could not be found. Are you missing an assembly reference?
[Unity] Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/GLTFSceneImporter.cs(803,68): error CS0246: The type or namespace name `GLTF' could not be found. Are you missing an assembly reference?

**Comment by mr0ng** [comment]
I can confirm this issue. We worked around it by #if UNITY_IOS on all GLTF related scripts and was able to successfully build to iOS, but it would be nice to know if there was a way for those gltf components to work in iOS

**Comment by keveleigh** [comment]
There is a GLTFSerialization DLL that isn't being included on certain platforms by default. Checking that DLL and making sure to include it on iOS should resolve this issue.

I previously updated the DLL to explicitly exclude UWP instead of explicitly including Editor and Standalone, as that causes this issue (platforms not accounted for become excluded by default). Unfortunately, that was reverted due to 5.6 incompatibility, but we should be able to include it now after the most recent Toolkit release. I'll open a PR on Monday.

**Comment by keveleigh** [comment]
I've introduced a possible fix in #2361, though I don't have a set-up to check building on iOS. I replicated a similar scenario though, which did not work before that change and does work after.

**Comment by mr0ng** [comment]
@keveleigh I didn't try your new PR, but tried including iOS in the DLL you mention:
![image](https://user-images.githubusercontent.com/19508106/42107576-ca8eaf3c-7b8c-11e8-94ac-c04143671ce3.png)
However, it looks like I still get a build error, although a different one. I will look at newtonsoftJSON to see if there's an iOS dependency not included there

**Comment by mr0ng** [comment]
I included newtonsoft with iOS:
![image](https://user-images.githubusercontent.com/19508106/42108001-22b637e2-7b8e-11e8-9f97-578d99292817.png)

But I'm still getting the newtonsoft error when building:
![image](https://user-images.githubusercontent.com/19508106/42108030-348292ea-7b8e-11e8-8d0c-b5b06149da2c.png)

**Comment by keveleigh** [comment]
Strange. I wonder if this is related to #2269.

**Comment by mr0ng** [comment]
Ok, I will attempt to import the new newtonsoft per the other issue you referenced. Here's the error I'm getting with the current newtonsoft:

`Exception: D:\Program Files Surface Book\Unity\Editor\2018.1.0f2\Editor\Data\il2cpp/build/UnityLinker.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1 setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.AssemblyStripper.RunAssemblyLinker (IEnumerable`1 args, System.String& out, System.String& err, System.String linkerPath, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:89)
UnityEditorInternal.AssemblyStripper.StripAssembliesTo (System.String[] assemblies, System.String[] searchDirs, System.String outputFolder, System.String workingDirectory, System.String& output, System.String& error, System.String linkerPath, IIl2CppPlatformProvider platformProvider, IEnumerable`1 additionalBlacklist) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:82)
UnityEditorInternal.AssemblyStripper.RunAssemblyStripper (IEnumerable assemblies, System.String managedAssemblyFolderPath, System.String[] assembliesToStrip, System.String[] searchDirs, System.String monoLinkerPath, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:203)
UnityEditorInternal.AssemblyStripper.StripAssemblies (System.String managedAssemblyFolderPath, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:113)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:154)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:35)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (BuildSettings bs, UnityEditor.iOS.ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:803)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (BuildSettings bs, UnityEditor.iOS.ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:639)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (PostProcessorSettings postProcessorSettings, BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:592)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:37)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at C:/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:27)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTargetGroup targetGroup, BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:285)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by mr0ng** [comment]
@keveleigh Great news, it worked! So to recap:
1. Import the new newtonsoft as recommended in #2269 - be sure to import only the AOT version of that DLL
2. Set the new newtonsoft to iOS but disable WSA and other platforms on the new DLL
3. Include iOS in the GLTFSerialization DLL 

Note: This still doesn't build to iOS on Windows, but does build to iOS on a Mac.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
