### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by junpark12** [microsoft/MixedRealityToolkit-Unity#4712]
## Overview
When I try to build mrtk v2 RC1 refresh based scene, i receive build error in unity.
Here is my configuration.
![image](https://user-images.githubusercontent.com/20918194/58933805-6676ee00-87a3-11e9-91fe-1dbd46ab917a.png)
![image](https://user-images.githubusercontent.com/20918194/58933833-7bec1800-87a3-11e9-9986-4367ed9537b3.png)
Here is the error message in Unity.
![image](https://user-images.githubusercontent.com/20918194/58933927-cbcadf00-87a3-11e9-94ef-76bd1addf97f.png)

I added newton.json.dll reference , so i copied following dll into Plugins\WSA folder. 
Newtonsoft.Json.6.0.4\lib\netcore45\Newtonsoft.Json.dll 

Here's configuation of the dll. 
![image](https://user-images.githubusercontent.com/20918194/58934038-32e89380-87a4-11e9-9bf3-730d74b79a8b.png)

If i change backend script as IL2CPP, it create project files without any errors.
But i want to create c# project instead of IL2CPP. 

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
Unity 2018.3.14f1 (64-bit)
## Mixed Reality Toolkit Release Version
MRTK v2 RC1 Refresh

**Comment by wiwei** [comment]
We fixed a couple of .NET scripting backend bugs over the past month - though to be totally honest I forget if those were part of the refresh or if they came later.

Nevertheless, we actually added a .NET scripting backend step to our CI build, so if you pull from the latest mrtk_development branch (or the prerelease/2.0.0.rc2_stabilization branch) .NET should be good.

As for the errors there, note that some Assembly Rewriter errors are known (if you post the full text we could confirm) and we've followed up with Unity to get those addressed.

For concrete next steps, I'd recommend switching over to one of those mentioned branches (probably the stabilization branch)

**Comment by junpark12** [comment]
Here's the error. It's no hurry. So if this is related to bugs already fixed then i'll just wait for RC2.
Please just make sure this is the bug already fixed. Thanks .

UnityException: Failed to run reference rewriter with command "--target=Temp\StagingArea\Assembly-CSharp.dll" "--target=Temp\StagingArea\Unity.Analytics.DataPrivacy.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Utilities.Gltf.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.TeleportSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.SpatialAwarenessSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.InputSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.DiagnosticsSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.BoundarySystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.SDK.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsVoiceInput.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Core.Utilities.Async.dll" "--target=Temp\StagingArea\Unity.TextMeshPro.dll" "--target=Temp\StagingArea\Unity.XR.WindowsMR.dll" "--target=Temp\StagingArea\UnityEngine.Timeline.dll" "--target=Temp\StagingArea\Newtonsoft.Json.dll" "--target=Temp\StagingArea\UnityEngine.UI.dll" "--target=Temp\StagingArea\UnityEngine.SpatialTracking.dll" "--target=Temp\StagingArea\Unity.Analytics.Tracker.dll" "--target=Temp\StagingArea\Unity.Analytics.StandardEvents.dll" "--target=Temp\StagingArea\UnityEngine.Networking.dll" "--target=Temp\StagingArea\Microsoft.AspNet.SignalR.Client.dll" "--additionalreferences=Temp\StagingArea,Temp\StagingArea\Plugins\X64,Temp\StagingArea\Plugins\ARM,Temp\StagingArea\Plugins\ARM64,Temp\StagingArea\Plugins\X86,C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.MachineLearningContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsPhoneContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsVoipContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.StartupTaskContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.PrintersContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.XboxLive.StorageApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Graphics.Printing3D.Printing3DContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Sockets.ControlChannelTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.GuidanceContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.LocalSearchContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Store.StoreContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.SystemManagementContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Core.Direct.XamlDirectContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.SearchContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Input.GamingInputPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Preview.GamesEnumerationContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GameChatOverlayContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GamingUIProviderContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppBroadcasting.AppBroadcastingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppRecording.AppRecordingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppBroadcastContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureMetadataContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.GameBarContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Devices.CallControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.MediaControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Playlists.PlaylistsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.XboxLive.XboxLiveSecureSocketsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.EnterpriseData.EnterpriseDataContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Storage.Provider.CloudFilesContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Shell.SecurityAppManagerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Hosting.HostingContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.PhoneContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" "--platform=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade\Windows.winmd" "--dbg=pdb" "--support=Temp\StagingArea\WinRTLegacy.dll" "--supportpartialns=Unity.Partial" "--system=System" "--lock=UWP\project.lock.json" "--alt=Microsoft.Win32.SafeHandles,System.IO.FileSystem;Microsoft.Win32.SafeHandles,System.Runtime.Handles;System,System.ComponentModel;System,System.Data.Common;System,System.Runtime;System,System.Runtime.Extensions;System,System.Runtime.InteropServices;System,System.Threading.Tasks;System.CodeDom.Compiler,System.Diagnostics.Tools;System.Collections,System.Collections;System.Collections,System.Collections.NonGeneric;System.Collections,System.Runtime;System.Collections.Generic,System.Collections;System.Collections.Generic,System.Runtime;System.Collections.ObjectModel,System.ObjectModel;System.Collections.ObjectModel,System.Runtime;System.Collections.Specialized,System.Collections.NonGeneric;System.Collections.Specialized,System.Collections.Specialized;System.Collections.Specialized,System.ObjectModel;System.ComponentModel,Microsoft.Win32.Primitives;System.ComponentModel,System.ComponentModel;System.ComponentModel,System.ComponentModel.EventBasedAsync;System.ComponentModel,System.ObjectModel;System.ComponentModel,System.Runtime;System.ComponentModel.DataAnnotations,System.ComponentModel.Annotations;System.Data,System.Data.Common;System.Data.Common,System.Data.Common;System.Diagnostics,System.Diagnostics.Debug;System.Diagnostics,System.Diagnostics.StackTrace;System.Diagnostics,System.Runtime;System.Diagnostics,System.Runtime.Extensions;System.Diagnostics.CodeAnalysis,System.Diagnostics.Tools;System.Globalization,System.Globalization;System.Globalization,System.Globalization.Calendars;System.Globalization,System.Globalization.Extensions;System.Globalization,System.Runtime;System.IO,System.IO;System.IO,System.IO.FileSystem;System.IO,System.IO.FileSystem.Primitives;System.IO,System.IO.UnmanagedMemoryStream;System.IO,System.Runtime;System.IO,System.Runtime.Extensions;System.IO,System.Runtime.Handles;System.IO.Compression,System.IO.Compression;System.IO.IsolatedStorage,System.IO.IsolatedStorage;System.Linq,System.Linq;System.Linq,System.Linq.Expressions;System.Linq,System.Linq.Queryable;System.Linq.Expressions,System.Linq.Expressions;System.Net,System.Net.Primitives;System.Net,System.Net.Requests;System.Net,System.Net.WebHeaderCollection;System.Net.NetworkInformation,System.Net.NetworkInformation;System.Net.NetworkInformation,System.Net.Primitives;System.Net.Security,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Net.Sockets,System.Net.Sockets;System.Reflection,System.Reflection;System.Reflection,System.Reflection.Extensions;System.Reflection,System.Reflection.Primitives;System.Reflection,System.Reflection.TypeExtensions;System.Reflection,System.Runtime;System.Reflection,System.Runtime.InteropServices;System.Reflection.Emit,System.Reflection.Primitives;System.Resources,System.Resources.ResourceManager;System.Runtime,System.Runtime;System.Runtime.CompilerServices,System.Runtime;System.Runtime.InteropServices,System.Runtime;System.Runtime.InteropServices,System.Runtime.Handles;System.Runtime.InteropServices,System.Runtime.InteropServices;System.Runtime.InteropServices.ComTypes,System.Runtime.InteropServices;System.Runtime.Serialization,System.Runtime.Serialization.Primitives;System.Runtime.Serialization,System.Runtime.Serialization.Xml;System.Runtime.Serialization.Json,System.Runtime.Serialization.Json;System.Security,System.Runtime;System.Security.Authentication,System.Net.Primitives;System.Security.Principal,System.Security.Claims;System.Security.Principal,System.Security.Principal;System.ServiceModel,System.ServiceModel.Duplex;System.ServiceModel,System.ServiceModel.Http;System.ServiceModel,System.ServiceModel.NetTcp;System.ServiceModel,System.ServiceModel.Primitives;System.ServiceModel,System.ServiceModel.Security;System.ServiceModel.Channels,System.ServiceModel.Http;System.ServiceModel.Channels,System.ServiceModel.NetTcp;System.ServiceModel.Channels,System.ServiceModel.Primitives;System.Serv<message truncated>

**Comment by Yoyozilla** [comment]
@junpark12 could i suggest you try unity 2018.3.7 to see if the error persist?

**Comment by junpark12** [comment]
Hi i upgraded to "v2.0.0 RC2.1" but still receive the same error message when i build.

UnityException: Failed to run reference rewriter with command "--target=Temp\StagingArea\Assembly-CSharp.dll" "--target=Temp\StagingArea\MixedRealityToolkit.Services.CameraSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Utilities.Gltf.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.TeleportSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.SpatialAwarenessSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.InputSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.InputSimulation.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.DiagnosticsSystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Services.BoundarySystem.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.SDK.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsVoiceInput.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.dll" "--target=Temp\StagingArea\Microsoft.MixedReality.Toolkit.Core.Utilities.Async.dll" "--target=Temp\StagingArea\Unity.Analytics.DataPrivacy.dll" "--target=Temp\StagingArea\Unity.TextMeshPro.dll" "--target=Temp\StagingArea\Unity.XR.WindowsMR.dll" "--target=Temp\StagingArea\UnityEngine.Timeline.dll" "--target=Temp\StagingArea\Newtonsoft.Json.dll" "--target=Temp\StagingArea\UnityEngine.UI.dll" "--target=Temp\StagingArea\UnityEngine.SpatialTracking.dll" "--target=Temp\StagingArea\Unity.Analytics.Tracker.dll" "--target=Temp\StagingArea\Unity.Analytics.StandardEvents.dll" "--target=Temp\StagingArea\UnityEngine.Networking.dll" "--target=Temp\StagingArea\Microsoft.AspNet.SignalR.Client.dll" "--additionalreferences=Temp\StagingArea,Temp\StagingArea\Plugins\X64,Temp\StagingArea\Plugins\ARM,Temp\StagingArea\Plugins\ARM64,Temp\StagingArea\Plugins\X86,C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.MachineLearningContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsPhoneContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.CallsVoipContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.SocialInfo.SocialInfoContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.StartupTaskContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.DevicesLowLevelContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.PrintersContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.SmartCards.SmartCardEmulatorContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.UniversalApiContract\8.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.XboxLive.StorageApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Graphics.Printing3D.Printing3DContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.Sockets.ControlChannelTriggerContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.GuidanceContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Maps.LocalSearchContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.Store.StoreContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Services.TargetedContent.TargetedContentContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileSharedModeContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.SystemManagementContract\6.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Core.Direct.XamlDirectContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Search.SearchContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Input.GamingInputPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.Preview.GamesEnumerationContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GameChatOverlayContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Gaming.UI.GamingUIProviderContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppBroadcasting.AppBroadcastingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.AppRecording.AppRecordingContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppBroadcastContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.AppCaptureMetadataContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Capture.GameBarContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Devices.CallControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.MediaControlContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Playlists.PlaylistsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.XboxLive.XboxLiveSecureSocketsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.EnterpriseData.EnterpriseDataContract\5.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Storage.Provider.CloudFilesContract\3.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Shell.SecurityAppManagerContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.Xaml.Hosting.HostingContract\4.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.PhoneContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0,C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" "--platform=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0\Facade\Windows.winmd" "--dbg=pdb" "--support=Temp\StagingArea\WinRTLegacy.dll" "--supportpartialns=Unity.Partial" "--system=System" "--lock=UWP\project.lock.json" "--alt=Microsoft.Win32.SafeHandles,System.IO.FileSystem;Microsoft.Win32.SafeHandles,System.Runtime.Handles;System,System.ComponentModel;System,System.Data.Common;System,System.Runtime;System,System.Runtime.Extensions;System,System.Runtime.InteropServices;System,System.Threading.Tasks;System.CodeDom.Compiler,System.Diagnostics.Tools;System.Collections,System.Collections;System.Collections,System.Collections.NonGeneric;System.Collections,System.Runtime;System.Collections.Generic,System.Collections;System.Collections.Generic,System.Runtime;System.Collections.ObjectModel,System.ObjectModel;System.Collections.ObjectModel,System.Runtime;System.Collections.Specialized,System.Collections.NonGeneric;System.Collections.Specialized,System.Collections.Specialized;System.Collections.Specialized,System.ObjectModel;System.ComponentModel,Microsoft.Win32.Primitives;System.ComponentModel,System.ComponentModel;System.ComponentModel,System.ComponentModel.EventBasedAsync;System.ComponentModel,System.ObjectModel;System.ComponentModel,System.Runtime;System.ComponentModel.DataAnnotations,System.ComponentModel.Annotations;System.Data,System.Data.Common;System.Data.Common,System.Data.Common;System.Diagnostics,System.Diagnostics.Debug;System.Diagnostics,System.Diagnostics.StackTrace;System.Diagnostics,System.Runtime;System.Diagnostics,System.Runtime.Extensions;System.Diagnostics.CodeAnalysis,System.Diagnostics.Tools;System.Globalization,System.Globalization;System.Globalization,System.Globalization.Calendars;System.Globalization,System.Globalization.Extensions;System.Globalization,System.Runtime;System.IO,System.IO;System.IO,System.IO.FileSystem;System.IO,System.IO.FileSystem.Primitives;System.IO,System.IO.UnmanagedMemoryStream;System.IO,System.Runtime;System.IO,System.Runtime.Extensions;System.IO,System.Runtime.Handles;System.IO.Compression,System.IO.Compression;System.IO.IsolatedStorage,System.IO.IsolatedStorage;System.Linq,System.Linq;System.Linq,System.Linq.Expressions;System.Linq,System.Linq.Queryable;System.Linq.Expressions,System.Linq.Expressions;System.Net,System.Net.Primitives;System.Net,System.Net.Requests;System.Net,System.Net.WebHeaderCollection;System.Net.NetworkInformation,System.Net.NetworkInformation;System.Net.NetworkInformation,System.Net.Primitives;System.Net.Security,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Net.Sockets,System.Net.Sockets;System.Reflection,System.Reflection;System.Reflection,System.Reflection.Extensions;System.Reflection,System.Reflection.Primitives;System.Reflection,System.Reflection.TypeExtensions;System.Reflection,System.Runtime;System.Reflection,System.Runtime.InteropServices;System.Reflection.Emit,System.Reflection.Primitives;System.Resources,System.Resources.ResourceManager;System.Runtime,System.Runtime;System.Runtime.CompilerServices,System.Runtime;System.Runtime.InteropServices,System.Runtime;System.Runtime.InteropServices,System.Runtime.Handles;System.Runtime.InteropServices,System.Runtime.InteropServices;System.Runtime.InteropServices.ComTypes,System.Runtime.InteropServices;System.Runtime.Serialization,System.Runtime.Serialization.Primitives;System.Runtime.Serialization,System.Runtime.Serialization.Xml;System.Runtime.Serialization.Json,System.Runtime.Serialization.Json;System.Security,System.Runtime;System.Security.Authentication,System.Net.Primitives;System.Security.Principal,System.Security.Claims;System.Security.Principal,System.Security.Principal;System.ServiceModel,System.ServiceModel.Duplex;System.ServiceModel,System.ServiceModel.Http;System.ServiceModel,System.ServiceModel.NetTcp;System.ServiceModel,System.ServiceModel.Primitives;System.ServiceModel,System.ServiceModel.Security;System.ServiceModel<message truncated>

**Comment by wiwei** [comment]
@junpark12, are you still seeing this? We've since added a .NET CI build machine that builds appx-es, so I'm curious if you're still having this issue.

**Comment by Troy-Ferrell** [comment]
Closing due to inactivity
