### ISSUE TITLE
UnityUI far interaction in Play Mode Tests, batch mode does not work 

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5887]
## Overview
We should be able to use hand rays to interact with UnityUI in our playmode tests, however using far interaction with UnityUI doesn't actually in playmode tests when running in batch mode. Things run fine in the Unity Editor

## Repro steps
1. In PressableButtonTests.TriggerButtonFarInteraction(), remove the block which does Asset.Ignore() and yield break;
2. Run the test in batch mode
  a. Run this command
`     .\run_playmode_tests.ps1 H:\mrtk.dev -unityExePath = "C:\Program Files\Unity\Hub\Editor\2018.4.1f1\Editor\Unity.exe"`
  b. Tip, you can edit run_playmode_tests.ps1 to run only this test by adding this to the Unity command line args around line 37
`     "-editorTestsFilter TriggerButtonFarInteraction",`

## Expected
Both variants of the test (collider based prefab and unity ui based prefab) should pass in Editor and in batch/headless mode.

## Actual
The unity ui variant of TriggerButtonFarInteraction works in Editor but fails in batch/headless mode.
## Expected Behavior
Tests pass

## Actual Behavior
Test fails

**Comment by AdamMitchell-ms** [comment]
## Repro steps

1. In PressableButtonTests.TriggerButtonFarInteraction(), remove the block which does Asset.Ignore() and yield break;
2. Run the test in batch mode
  a. Run this command
`     .\run_playmode_tests.ps1 H:\mrtk.dev -unityExePath = "C:\Program Files\Unity\Hub\Editor\2018.4.1f1\Editor\Unity.exe"`
  b. Tip, you can edit run_playmode_tests.ps1 to run only this test by adding this to the Unity command line args around line 37
`     "-editorTestsFilter TriggerButtonFarInteraction",`

## Expected
Both variants of the test (collider based prefab and unity ui based prefab) should pass in Editor and in batch/headless mode.

## Actual
The unity ui variant of TriggerButtonFarInteraction works in Editor but fails in batch/headless mode.

**Comment by julenka** [comment]
RE-opening as I believe this bug still exists (nobody has made fixes to hand rays with UnityUI)

**Comment by keveleigh** [comment]
@MaxWang-MS found this was fixed, and re-enabled in #8790

**Comment by MaxWang-MS** [comment]
Note: The tests can now pass because the `Interactable` script has been added to the pressable button UnityUI prefab. The issue of UGUI `Button` script not correctly responding to press in batch mode tests is still present.

**Comment by keveleigh** [comment]
@MaxWang-MS Do you think this is fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8837? It wouldn't surprise me if the input module was previously failing to initialize on batch mode.

**Comment by MaxWang-MS** [comment]
@keveleigh I am not completely certain if that is the case, but given we currently have no tests that are potentially impacted by this could-have-been-fixed bug I'll just close the issue for now.
