### ISSUE TITLE
Hand Menu Does Not work in XRSDK

### ISSUE THREAD

**Issue by Tabsher2** [microsoft/MixedRealityToolkit-Unity#8377]
## Describe the bug

Attempting to use the hand menu whilst using the XRSDK does not work. The hand menu does not appear when the palm is seen.

## To reproduce

1. Create Unity Project with MRTK 2.4 in Unity 2019.4.2f1
2. Ensure XR Plugin Management, Windows XR Plugin, and XR Legacy Input Helpers are installed from the Package Manager.
3. Open the "HandMenuExamples" scene from the MRTK 2.4 Examples unity package.
4. Switch the Configuration Profile to default XRSDK configuration profile.
5. Build and deploy to HoloLens 2 with Master Solution Configuration and ARM64 as the Solution Platform.
6. Open app and attempt to use hand menus.

## Expected behavior

Menus should appear above / next to the user's hands when the palms are seen.

## Screenshots

The following error messages are thrown (depending on which hand the user attempts to use):

"HandConstraintPalmUp requires a palm joint, but none was provided by ArticulatedHand Controller Left."
"HandConstraintPalmUp requires a palm joint, but none was provided by ArticulatedHand Controller Right."

## Your setup (please complete the following information)

- Unity 2019.4.2f1
- Visual Studio 2019 v16.5.4
- MRTK 2.4
- XR SDK
- ARM64

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Upon my own investigation through the MRTK documentation, I believe the error might lie in the XRSDK Windows Mixed Reality Device Manager input provider, as according to the documentation, the Windows Mixed Reality Device Manager is what is supposed to provide WMR Articulated Hand control and according to the error message, that is what is failing.

**Comment by wiwei** [comment]
@Tabsher2 are you building ARM64 or ARM (32)?

**Comment by Tabsher2** [comment]
ARM64 sorry, let me add that to the description.

**Comment by laultman** [comment]
I am having a similar issue. I have been unable to get BoundingBox to work with XRSDK as well. I am also unable to get the Hand interaction examples from the toolkit to work on HoloLens 2 at all. I have at this point reverted back to Unity 2019.2.3 as described in the Microsoft Learning tutorial using the described configuration profile without XRSDK and still there is no menus appearing as expected. I am building on current VS2019. I have tried these Unity version, 2019.2.3, 2019.3.1, 2019.4.5, 2019.4.8, 2020.1 all with MRTK 2.4.0. My experience is thus far, nothing works as expected. I can get something working and something else breaks. Things work in Unity Player but fail on the HoloLens 2 device. So much does not work that it is difficult to tell where the bugs are. I am not seeing any errors on HoloLens 2 displayed, it simply fails to function silently.

**Comment by laultman** [comment]
Follow up comment, my VS2019 configuration is Release, ARM64.

**Comment by Tabsher2** [comment]
Some configuration profile changes between the 2.4 release and [current dev branch](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/e122f3ad81d65dc369c7e17fa8d83d691c027c4d) seems to have fixed the issue.

**Comment by LeoQIao** [comment]
@Tabsher2 Hey,I am use MRTK2.4 on Unity 2019.4.4f1, I just trying to fix the issue follow the [current dev branch](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/e122f3ad81d65dc369c7e17fa8d83d691c027c4d) that you mentioned above, but the hand menu still doesn't work.
How can I fix it on MRTK2.4?Thanks

**Comment by keveleigh** [comment]
This was fixed for the upcoming 2.5 release and in the dev branch via https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8328, adding the Hand Joint Service to the input profile. You should be able to add it manually on previous releases to fix the hand menus.

**Comment by LeoQIao** [comment]
> This was fixed for the upcoming 2.5 release and in the dev branch via #8328, adding the Hand Joint Service to the input profile. You should be able to add it manually on previous releases to fix the hand menus.

Great!Thank You!

**Comment by Zulex** [comment]
@Tabsher2 , @LeoQIao 

How have you been able to fix this issue? Our application works on mrtk 2.4 and works fine in editor after adding the hand joint service. But when deploying to the hololens 2 the hand menu does not show up at all. 
Using master build for arm64. Object interaction does work, so hands are being tracked correctly.

**Comment by LuuSangCntt** [comment]
I am using MRTK 2.6 on Unity 2020.3. The HandMenus works but I still receive this error

**Comment by konstyanchev** [comment]
This warning also appears to me, using MRTK 2.7 on Unity 2019.4.24f1. It appears when I use the HandMenu_Small_HideOnHandDrop prefab. I think that the warning occurs whenever the tracked palm becomes visible or becomes hidden from the hololens. I can reliably get this warning if I but my tracked hand behind my back, hiding it from the hololens and then bringing it back up.

**Comment by AdCCooN** [comment]
On MRTK 2.6.1 and Unity 2020.3.6f1 the menu works but error persists and seems that it is causing also a pretty major FPS drop...

**Comment by dnlwbr** [comment]
The same is the case for MRTK 2.7.2 and Unity 2020.3.16f1. The menu works, but the error messages still occur.

**Comment by Piflik** [comment]
Still the same issue with MRTK 2.7.2 and Unity 2020.3.20f1. Really annoying.
